CONTAINER VPfadeout
{
	NAME VPfadeout;

	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		REAL VPFADEOUT_TRANSPARENCY { UNIT PERCENT; STEP 1.0; MIN 0.0; MAX 100.0; }
		FILENAME VPFADEOUT_FILENAME { }
	}
}
