CONTAINER Prefstimeline
{
	NAME Prefstimeline;
	GROUP PREF_TL_MAIN_GROUP
	{
	
		DEFAULT 1;
		COLUMNS 2;
		
		SEPARATOR PREF_TL_DISPLAYGROUP {}
		STATICTEXT {JOINENDSCALE;}
		BOOL PREF_TL_INDICATOR {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_INTERACTIVE {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_HIGHLIGHT {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_HIGHLIGHTCURVE {ANIM OFF;}
		STATICTEXT{}
		
		SEPARATOR PREF_TL_OBJECTGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		BOOL PREF_TL_SHOWBRANCHES {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_SHOWVECTOR {ANIM OFF;}
		STATICTEXT{}
		
		SEPARATOR PREF_TL_KEYGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		BOOL PREF_TL_SUMMARY {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_TRACKSTARTEND {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_DOPESHEET {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_KEYSYMBOLS {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_LAYERCOL {ANIM OFF;}
		STATICTEXT{}
					
		LONG PREF_TL_TRACKCOL
		{
			ANIM OFF;
			CYCLE
			{
				PREF_TL_TRACKCOL_COL;
				PREF_TL_TRACKCOL_PSR;
				PREF_TL_TRACKCOL_NO;

			}
		}
		STATICTEXT{}
			
		LONG PREF_TL_KEYWIDTHVALUE {ANIM OFF; MIN 1.0; MAX 100;}
		STATICTEXT{}
		
		SEPARATOR PREF_TL_FCGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		
		REAL PREF_TL_RMREDUCTION {ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100.0;}
		STATICTEXT{}
		
		
		SEPARATOR PREF_TL_MOTIONGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		
		BASETIME PREF_TL_MOTION {ANIM OFF; MIN 0;}
		STATICTEXT{}
		
		
	}
}
