CONTAINER TLWorld
{
	NAME TLWorld;
	

	GROUP TLWORLD_GROUP
	{
	
		DEFAULT	1;
		COLUMNS 2;
	
		BOOL TLWORLD_OVERDUB  {ANIM OFF;}
		LONG TLWORLD_INTER    {ANIM OFF; CYCLE { TLWORLD_INTER_SP; TLWORLD_INTER_LI; TLWORLD_INTER_ST; } } 
		
		BOOL TLWORLD_LOCKV  {ANIM OFF;}
		BOOL TLWORLD_LOCKT  {ANIM OFF;}
		
		BOOL TLWORLD_AUTO  {ANIM OFF;}
		BOOL TLWORLD_CLAMP  {ANIM OFF;}
		
		BOOL TLWORLD_LOCKTA  {ANIM OFF;}
		BOOL TLWORLD_LOCKTL  {ANIM OFF;}
		
		BOOL TLWORLD_BREAK  {ANIM OFF;}
		BOOL TLWORLD_KEEPVISUALANGLE  {ANIM OFF;}
	
	}
}
