CONTAINER CKvalue
{
	NAME CKvalue;
//	INCLUDE CKbase;

	GROUP ID_VKEY_PROPERTIES
	{
		DEFAULT	1;
		COLUMNS 2;

		BASETIME ID_VKEY_TIME {} BOOL ID_VKEY_LOCK_T {}
		REAL ID_CKEY_VALUE    {} BOOL ID_CKEY_LOCK_V {}

		LONG ID_CKEY_INTER    { CYCLE { ID_CKEY_SPLINE; ID_CKEY_LINEAR; ID_CKEY_STEP; } } BOOL ID_VKEY_MUTE { }
		STATICTEXT {} BOOL ID_VKEY_BREAKDOWN  {}

		SEPARATOR { LINE; } STATICTEXT { JOINEND; }

		BOOL ID_CKEY_AUTO  {} BOOL ID_CKEY_CLAMP {}

		SEPARATOR { LINE; } STATICTEXT { JOINEND; }

		BASETIME ID_CKEY_TIME_LEFT	{MAX 0.0; }  BASETIME ID_CKEY_TIME_RIGHT  { MIN 0.0; }
		REAL     ID_CKEY_VALUE_LEFT	{}  REAL     ID_CKEY_VALUE_RIGHT {}

		SEPARATOR { LINE; } STATICTEXT { JOINEND; }

		//BOOL ID_CKEY_ZERO_O {} 
		BOOL ID_CKEY_LOCK_O {}
		//BOOL ID_CKEY_ZERO_L {} 
		BOOL ID_CKEY_LOCK_L {}
		BOOL ID_CKEY_BREAK  {} 
		BOOL ID_CKEY_KEEPVISUALANGLE  {} 
		STATICTEXT { }
		

	}
}
