CONTAINER dmodeling
{
  NAME dmodeling;

	GROUP SNAP_SETTINGS
	{
		BOOL SNAP_SETTINGS_ENABLED { ANIM OFF; }
		BOOL SNAP_SETTINGS_TOOL { ANIM OFF; }
		
		LONG SNAPMODE_COMBO
		{
		//ANIM OFF;
		CYCLE

			{


			}
		}

			
		SEPARATOR { LINE; }

		REAL SNAP_SETTINGS_RADIUS { UNIT REAL; MIN 0.1; MAX 100; ANIM OFF; }
		REAL SNAP_SETTINGS_GUIDEANGLE { UNIT DEGREE; MIN 0.1; MAX 180.0; STEP 1.0; ANIM OFF; }

		SEPARATOR { LINE; }
		
		BOOL SNAPMODE_POINT { ANIM OFF; }
		BOOL SNAPMODE_EDGE	{ ANIM OFF; }
		BOOL SNAPMODE_POLYGON { ANIM OFF; }
		BOOL SNAPMODE_SPLINE { ANIM OFF; }
		BOOL SNAPMODE_AXIS  { ANIM OFF; }
		BOOL SNAPMODE_INTERSECTION { ANIM OFF; }
		BOOL SNAPMODE_MIDPOINT { ANIM OFF; }
		
		SEPARATOR { LINE; }

		BOOL SNAPMODE_WORKPLANE { PARENTCOLLAPSE; ANIM OFF; }
		BOOL SNAPMODE_GRIDPOINT  { PARENTCOLLAPSE SNAPMODE_WORKPLANE; ANIM OFF; }
		BOOL SNAPMODE_GRIDLINE  { PARENTCOLLAPSE SNAPMODE_WORKPLANE; ANIM OFF; }

		BOOL SNAPMODE_GUIDE { PARENTCOLLAPSE; ANIM OFF; }
		BOOL SNAPMODE_DYNAMICGUIDE { PARENTCOLLAPSE SNAPMODE_GUIDE; ANIM OFF; }
		BOOL SNAPMODE_ORTHO  { PARENTCOLLAPSE SNAPMODE_GUIDE; ANIM OFF; }

		SEPARATOR { LINE; }

		GROUP SNAP_LIST
		{
		}
	}

	GROUP QUANTIZE_SETTINGS
	{
		BOOL QUANTIZE_ENABLED { ANIM OFF; }
		SEPARATOR { LINE; }
		REAL QUANTIZE_MOVE { UNIT METER; MIN 0.01; MAXSLIDER 1000.0; STEP 1.0; ANIM OFF; }
		REAL QUANTIZE_SCALE { UNIT PERCENT; MIN 0.01; MAXSLIDER 100.0; STEP 1.0; ANIM OFF; }
		REAL QUANTIZE_ROTATE { UNIT DEGREE; MIN 0.1; MAX 180.0; STEP 1.0; ANIM OFF; }
		REAL QUANTIZE_TEXTURE { UNIT REAL; MIN 0.01; MAXSLIDER 1.0; STEP 0.01; ANIM OFF; }
	}

	GROUP GUIDES_SETTINGS
	{
		REAL SNAP_SETTINGS_GUIDEANGLE { UNIT DEGREE; MIN 0.1; MAX 180.0; STEP 1.0; ANIM OFF; }
	}
}