CONTAINER Osymmetry
{
	NAME Osymmetry;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SYMMETRYOBJECT_PLANE
		{
			CYCLE
			{
				SYMMETRYOBJECT_PLANE_XY;
				SYMMETRYOBJECT_PLANE_YZ;
				SYMMETRYOBJECT_PLANE_XZ;
			}
		}
		BOOL SYMMETRYOBJECT_WELD {}
		REAL SYMMETRYOBJECT_TOLERANCE { PARENTID SYMMETRYOBJECT_WELD; UNIT METER; MIN 0.0; }
		BOOL SYMMETRYOBJECT_ONPLANE { PARENTID SYMMETRYOBJECT_WELD; }
	}
}
