#ifndef OSYMMETRY_H__
#define OSYMMETRY_H__

enum
{
	SYMMETRYOBJECT_PLANE			= 1000,
		SYMMETRYOBJECT_PLANE_XY 	= 0,
		SYMMETRYOBJECT_PLANE_YZ 	= 1,
		SYMMETRYOBJECT_PLANE_XZ 	= 2,
	SYMMETRYOBJECT_WELD				= 1001,
	SYMMETRYOBJECT_TOLERANCE	= 1002,
	SYMMETRYOBJECT_ONPLANE		= 1003
};

#endif	// OSYMMETRY_H__
