CONTAINER Tmetaball
{
	NAME Tmetaball;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BOOL METABALLTAG_NEGATIVE {}
		REAL METABALLTAG_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 10000.0; }
		REAL METABALLTAG_RADIUS   { UNIT METER; MIN 0.0; }
	}
}
