#ifndef XXMBREFLECTION_H__
#define XXMBREFLECTION_H__

enum
{
	XMBREFLECTIONSHADER_COLOR 					= 1000,
	XMBREFLECTIONSHADER_BRIGHTNESS 					= 1001,

	XMBREFLECTIONSHADER_TEXTURE_SHADER				= 1010,
	XMBREFLECTIONSHADER_TEXTURE_MIXING 				= 1011,
	XMBREFLECTIONSHADER_TEXTURE_STRENGTH 				= 1012,
		XMBREFLECTIONSHADER_TEXTURE_MIXING_NORMAL		= 0,
		XMBREFLECTIONSHADER_TEXTURE_MIXING_ADD			= 1,
		XMBREFLECTIONSHADER_TEXTURE_MIXING_SUBTRACT		= 2,
		XMBREFLECTIONSHADER_TEXTURE_MIXING_MULTIPLY		= 3,

	XMBREFLECTIONSHADER_SAMPLES					= 1013,
	XMBREFLECTIONSHADER_BUMP					= 1014,

	XMBREFLECTIONSHADER_DISTRIBUTION				= 1020,
		XMBREFLECTIONSHADER_DISTRIBUTION_SIMPLE			= 0,
		XMBREFLECTIONSHADER_DISTRIBUTION_BLINN			= 1,
		XMBREFLECTIONSHADER_DISTRIBUTION_BECKMANN		= 2,
		XMBREFLECTIONSHADER_DISTRIBUTION_WARD			= 3,
		XMBREFLECTIONSHADER_DISTRIBUTION_ANISOTROPIC		= 4,

	XMBREFLECTIONSHADER_VALUE_ROUGHNESS 				= 1021,
	XMBREFLECTIONSHADER_VALUE_ANISOTROPY				= 1022,
	XMBREFLECTIONSHADER_VALUE_ORIENTATION				= 1023,

	XMBREFLECTIONSHADER_SHADER_ROUGHNESS 				= 1031,
	XMBREFLECTIONSHADER_SHADER_ANISOTROPY				= 1032,
	XMBREFLECTIONSHADER_SHADER_ORIENTATION				= 1033,

	XMBREFLECTIONSHADER_VALUE_FRESNEL_STRENGTH			= 1040,
	XMBREFLECTIONSHADER_VALUE_FRESNEL_RATIO				= 1041,
	XMBREFLECTIONSHADER_VALUE_FRESNEL_IOR				= 1042,
	XMBREFLECTIONSHADER_VALUE_FRESNEL_ABSORPTION			= 1043,

	XMBREFLECTIONSHADER_SHADER_FRESNEL_STRENGTH			= 1050,
	XMBREFLECTIONSHADER_SHADER_FRESNEL_RATIO			= 1051,
	XMBREFLECTIONSHADER_SHADER_FRESNEL_IOR				= 1052,
	XMBREFLECTIONSHADER_SHADER_FRESNEL_ABSORPTION			= 1053,


	XMBREFLECTIONSHADER_DEBUG_DUDV					= 1900,
		XMBREFLECTIONSHADER_DEBUG_DUDV_NORMAL			= 0,
		XMBREFLECTIONSHADER_DEBUG_DUDV_DEFAULT_U		= 1,
		XMBREFLECTIONSHADER_DEBUG_DUDV_DEFAULT_V		= 2,
		XMBREFLECTIONSHADER_DEBUG_DUDV_TANGENT_U		= 3,
		XMBREFLECTIONSHADER_DEBUG_DUDV_TANGENT_V		= 4,

};

#endif	// XXMBREFLECTION_H__
