CONTAINER XskyshaderVolume
{
	NAME XskyshaderVolume;
	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL SKY_VOL_MATERIAL_PAGE_PROPERTIES { PAGE; HIDDEN; PARENTMSG ID_MATERIALPROPERTIES; }
	}

	GROUP ID_MATERIALPROPERTIES
	{
		LINK SKY_VOL_MATERIAL_SKY_OBJ { HIDDEN; }
	}
}  
