// C4D Shortcut Resource
// Command	Shortcut

SHORTCUTTABLE
{
  IDM_BEENDEN	PC+ALT+F4;
  IDM_BEENDEN MAC+CTRLCMD+"Q";
  IDM_CUT	CTRLCMD+"X";
  IDM_COPY	CTRLCMD+"C";
  IDM_PASTE	CTRLCMD+"V";
  IDM_SELECTALL	CTRLCMD+"A";
  IDM_SELECTNONE	CTRLCMD+SHIFT+"A";
  PLUGIN_CMD_200000263	CTRLCMD+"E";
  // IDM_CONSOLE	F1;
}
	
