// Menudefinition for EDITOR

MENU M_EDITOR
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_1000474;
    SEPARATOR;
		IDM_SAVELAYOUTAS;
    SEPARATOR;
    PLUGIN_CMD_200000204;
    IDM_BEENDEN;
	}
	SUBMENU IDS_EDITOR_ABOUT
	{
    IDM_MAXONSUPPORT;
		SEPARATOR;
		IDM_UEBER;
	}
}
