// C4D-DialogResource
DIALOG IDD_CBPREFS
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC; ALIGN_TOP; FIT_H; 
    BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    COMBOBOX IDC_CB_LANGUAGE
    {
      ALIGN_TOP; SCALE_H; SIZE 150, 0; 
      CHILDS
      {
      }
    }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; CENTER_V; FIT_H; 
    BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 2;
    SPACE 4, 4;
    
    CHECKBOX IDC_CB_CUSTOMRENDERTHREADS { NAME IDS_CHECK; CENTER_V; ALIGN_LEFT;  }
    EDITNUMBERARROWS IDC_CB_CUSTOMRENDERTHREADS_CNT
    { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
  DLGGROUP { OK; CANCEL; }
}