CONTAINER Fobjimport
{
	NAME Fobjimport;
	INCLUDE Fbase;

	GROUP OBJIMPORTFILTER_GROUP
	{
		UNITSCALE OBJIMPORTFILTER_SCALE	{ }
		BOOL OBJIMPORTFILTER_IMPORTNORMALS { DEFAULT 1;}
		BOOL OBJIMPORTFILTER_OPTIMIZE {DEFAULT 1; }
	}
}
