CONTAINER Prefsunits
{
	NAME Prefsunits;
	GROUP PREF_UNITS_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
		
		SEPARATOR PREFS_UNITS_BASICGR {}
		STATICTEXT {JOINENDSCALE;}

		BOOL PREF_UNITS_DISPLAY	{ ANIM OFF; }
		STATICTEXT {}

		BOOL PREF_UNITS_AUTOCONVERT	{ ANIM OFF; }		
		STATICTEXT {}

		LONG PREF_UNITS_BASIC 
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_UNITS_BASIC_KM;
				PREF_UNITS_BASIC_M;
				PREF_UNITS_BASIC_CM;
				PREF_UNITS_BASIC_MM;
				PREF_UNITS_BASIC_MICRO;
				PREF_UNITS_BASIC_NM;
				PREF_UNITS_BASIC_MILE;
				PREF_UNITS_BASIC_YARD;
				PREF_UNITS_BASIC_FOOT;
				PREF_UNITS_BASIC_INCH;

			} 
		}
		STATICTEXT {}
		
		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}

		LONG PREF_UNITS_ANIMATION 
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_UNITS_ANIM_FPS;
				PREF_UNITS_ANIM_SEC;
				PREF_UNITS_ANIM_SMPTE;
			} 
		}
		STATICTEXT {}
		SEPARATOR PREFS_UNITS_COLORGROUP {}
		STATICTEXT {JOINENDSCALE;}
		
		BOOL PREF_UNITS_USESYSPICKER	{ ANIM OFF; }
		STATICTEXT {}
		
		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}
		
		LONG PREF_UNITS_C4DSYS
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_UNITS_SYS_RGB;
				PREF_UNITS_SYS_HSV;
				PREF_UNITS_SYS_SIMPLE;
				PREF_UNITS_SYS_ENHANCED;
			} 
		}
		STATICTEXT {}
		
		BOOL PREF_UNITS_C4DSTORAGE	{ ANIM OFF; }
		STATICTEXT {}
		BOOL PREF_UNITS_C4DPANEL	{ ANIM OFF; }
		STATICTEXT {}
		
		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}
		
		LONG PREF_UNITS_BPSYS
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_UNITS_SYS_RGB;
				PREF_UNITS_SYS_HSV;
				PREF_UNITS_SYS_SIMPLE;
				PREF_UNITS_SYS_ENHANCED;
			} 
		}
		STATICTEXT {}
		
		BOOL PREF_UNITS_BPSTORAGE	{ ANIM OFF; }
		STATICTEXT {}
		
		BOOL PREF_UNITS_BPPANEL	{ ANIM OFF; }
		STATICTEXT {}
		
		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}
		
		LONG PREF_UNITS_RGBRANGE
	  {
			ANIM OFF;
			CYCLE
			{
			  PREF_UNIT_RANGE_PERCENT; 
			  PREF_UNIT_RANGE_255; 
			  PREF_UNIT_RANGE_65535; 
			}
		}
		  
		STATICTEXT {}
		  
		LONG PREF_UNITS_HRANGE
		{
			ANIM OFF;
			CYCLE
			{
				PREF_UNIT_RANGE_PERCENT; 
				PREF_UNIT_RANGE_255; 
				PREF_UNIT_RANGE_DEGREE; 
				PREF_UNIT_RANGE_65535; 
			}
	  }
		  
	  STATICTEXT {}
		  
	  LONG PREF_UNITS_SVRANGE
	  {
			ANIM OFF;
			CYCLE
			{
			  0, PREF_UNIT_RANGE_PERCENT; 
			  1, PREF_UNIT_RANGE_255; 
			  2, PREF_UNIT_RANGE_65535; 
			}
	  }
		  
	  STATICTEXT {}
	}
}
