#ifndef PREFSUNITS_H__
#define PREFSUNITS_H__

enum
{
	PREF_UNITS_MAIN_GROUP			= 999,
	PREF_UNITS_DISPLAY				= 1000,
	PREF_UNITS_AUTOCONVERT		= 1001,
	PREF_UNITS_BASIC					= 1002,
		PREF_UNITS_BASIC_KM						= 1,
		PREF_UNITS_BASIC_M						= 2,
		PREF_UNITS_BASIC_CM						= 3,
		PREF_UNITS_BASIC_MM						= 4,
		PREF_UNITS_BASIC_MICRO				= 5,
		PREF_UNITS_BASIC_NM						=	6,
		PREF_UNITS_BASIC_MILE					= 7,
		PREF_UNITS_BASIC_YARD					= 8,
		PREF_UNITS_BASIC_FOOT					= 9,
		PREF_UNITS_BASIC_INCH					= 10,

	PREF_UNITS_ANIMATION			= 1003,
			PREF_UNITS_ANIM_FPS			= 0,
			PREF_UNITS_ANIM_SEC			= 1,
			PREF_UNITS_ANIM_SMPTE		= 2,
	PREF_UNITS_USESYSPICKER		= 1004,
	PREF_UNITS_C4DSYS					= 1005,
			PREF_UNITS_SYS_RGB				= 0,
			PREF_UNITS_SYS_HSV				= 1,
			PREF_UNITS_SYS_SIMPLE			= 2,
			PREF_UNITS_SYS_ENHANCED		= 3,
	PREF_UNITS_BPSYS					= 1006,
	PREF_UNITS_C4DSTORAGE			= 1007,
	PREF_UNITS_BPSTORAGE			= 1008,
	PREF_UNITS_C4DPANEL				= 1009,
	PREF_UNITS_BPPANEL				= 1010,
	PREF_UNITS_RGBRANGE				= 1011,
	PREF_UNITS_HRANGE					= 1012,
	PREF_UNITS_SVRANGE				= 1013,
	PREF_UNIT_RANGE_PERCENT			= 0,
	PREF_UNIT_RANGE_255					= 1,
	PREF_UNIT_RANGE_65535				= 2,
	PREF_UNIT_RANGE_DEGREE			= 3,

	//groups
	PREFS_UNITS_COLORGROUP					= 2000,
	PREFS_UNITS_BASICGR								= 2001,


	PREFS_UNITS_DUMMY
};

#endif	// PREFSUNITS_H__
