CONTAINER Prefscommunication
{
	NAME Prefscommunication;

	GROUP PREF_COMMUNICATION_MAINGROUP
	{
		DEFAULT 1;
		COLUMNS 1;
		
		BOOL PREF_COMMUNICATION_BUGREPORTS { ANIM OFF; }
		
		GROUP PREF_COMMUNICATION_UPDATEGROUP { }
		
		BOOL PREF_COMMUNICATION_UPDATE_AUTO { ANIM OFF; }
		BOOL PREF_COMMUNICATION_UPDATE_AUTO_DEVELOPER { ANIM OFF; }
		
		SEPARATOR {LINE;}
		
		GROUP
		{
			DEFAULT 1;
			COLUMNS 3;
			
			STRING	PREF_COMMUNICATION_PROXY_URL	{ ANIM OFF; }
			STATICTEXT {JOINENDSCALE;}
			LONG	PREF_COMMUNICATION_PROXY_PORT	{ ANIM OFF; MIN 0; MAX 65535; }
		}
	}
}
