#ifndef PREFSCOMMUNICATION_H__
#define PREFSCOMMUNICATION_H__

enum
{
	PREF_COMMUNICATION_MAINGROUP								= 999,
	PREF_COMMUNICATION_UPDATEGROUP							= 1012,
	PREF_COMMUNICATION_BUGREPORTS								= 1003,

	PREF_COMMUNICATION_UPDATE_AUTO							= 1000,
	PREF_COMMUNICATION_UPDATE_AUTO_DEVELOPER		= 1004,
	PREF_COMMUNICATION_UPDATE_BETASERVER				= 1999,

	PREF_COMMUNICATION_PROXY_URL								= 1001,
	PREF_COMMUNICATION_PROXY_PORT								= 1002,

	PREF_COMMUNICATION_DUMMY
};

#endif	// PREFSCOMMUNICATION_H__
